spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/onlineshop
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      enable-auto-commit: true
    producer:
      acks: 1
      retries: 3

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

openapi:
  title: notification
  version: 1.0.0
  description: notification sender app
  server-url: http://localhost:8080

# Настройки приложения
app:
  kafka:
    topic:
      notification: notification-topic
      partitions: 3
      replication-factor: 1
  firebase:
    enabled: false
    location: classpath:firebase/dev/notification.json