spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/onlineshop
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

openapi:
  title: notification
  version: 1.0.0
  description: notification sender app
  server-url: http://localhost:8080

app:
  firebase:
    enabled: false
    location: classpath:firebase/dev/notification.json