spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 9376570167
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      enable-auto-commit: true
    producer:
      acks: all
      retries: 5

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

openapi:
  title: notification
  version: 1.0.0
  description: notification sender app
  server-url: http://localhost:8080

# Настройки приложения
app:
  kafka:
    topic:
      notification: notification-topic
      partitions: 3
      replication-factor: 3
  firebase:
    enabled: false
    location: classpath:firebase/prod/notification.json